from __future__ import annotations

# ruff: noqa: F401, F403
from ._base import *

class BulkClientTemplateSelection(PasarguardModel):
    ids: Optional[List[int]] = None

class ClientTemplateCreate(PasarguardModel):
    name: str = ...
    template_type: ClientTemplateType = ...
    content: str = ...
    is_default: Optional[bool] = False

class ClientTemplateModify(PasarguardModel):
    name: Optional[str] = None
    content: Optional[str] = None
    is_default: Optional[bool] = None

class ClientTemplateResponse(PasarguardModel):
    id: int = ...
    name: str = ...
    template_type: ClientTemplateType = ...
    content: str = ...
    is_default: bool = ...
    is_system: bool = ...

class ClientTemplateResponseList(PasarguardModel):
    count: int = ...
    templates: Optional[List[ClientTemplateResponse]] = []

class ClientTemplateSimple(PasarguardModel):
    id: int = ...
    name: str = ...
    template_type: ClientTemplateType = ...
    is_default: bool = ...

class ClientTemplatesSimpleResponse(PasarguardModel):
    templates: List[ClientTemplateSimple] = ...
    total: int = ...

class RemoveClientTemplatesResponse(PasarguardModel):
    templates: List[str] = ...
    count: int = ...

__all__ = (
    'BulkClientTemplateSelection',
    'ClientTemplateCreate',
    'ClientTemplateModify',
    'ClientTemplateResponse',
    'ClientTemplateResponseList',
    'ClientTemplateSimple',
    'ClientTemplatesSimpleResponse',
    'RemoveClientTemplatesResponse',
)
