from __future__ import annotations

from ._base import Optional, PasarguardModel

class InboundSummary(PasarguardModel):
    tag: str = ...
    protocol: str = ...
    network: Optional[str] = None

class SystemStats(PasarguardModel):
    version: str = ...
    uptime_seconds: int = ...
    mem_total: Optional[int] = None
    mem_used: Optional[int] = None
    disk_total: Optional[int] = None
    disk_used: Optional[int] = None
    cpu_cores: Optional[int] = None
    cpu_usage: Optional[float] = None
    total_user: int = ...
    online_users: int = ...
    active_users: int = ...
    on_hold_users: int = ...
    disabled_users: int = ...
    expired_users: int = ...
    limited_users: int = ...
    incoming_bandwidth: int = ...
    outgoing_bandwidth: int = ...

class SystemUsersStats(PasarguardModel):
    total_user: int = ...
    online_users: int = ...
    active_users: int = ...
    on_hold_users: int = ...
    disabled_users: int = ...
    expired_users: int = ...
    limited_users: int = ...
    incoming_bandwidth: int = ...
    outgoing_bandwidth: int = ...

class SystemResourceStats(PasarguardModel):
    version: str = ...
    uptime_seconds: int = ...
    mem_total: Optional[int] = None
    mem_used: Optional[int] = None
    disk_total: Optional[int] = None
    disk_used: Optional[int] = None
    cpu_cores: Optional[int] = None
    cpu_usage: Optional[float] = None

class WorkerHealth(PasarguardModel):
    status: str = ...
    response_time_ms: Optional[int] = None
    error: Optional[str] = None

class WorkersHealth(PasarguardModel):
    scheduler: WorkerHealth = ...
    node: WorkerHealth = ...

__all__ = (
    'InboundSummary',
    'SystemResourceStats',
    'SystemStats',
    'SystemUsersStats',
    'WorkerHealth',
    'WorkersHealth',
)
